### ISSUE TITLE
Error on macos Big Sur

### ISSUE THREAD

**Issue by KeygenOld** [CatchZeng/bing_images#1]
Followed the install using anaconda. Script fires up Chrome and starts loading up images, but then runs into the following error and fails without any images being downloaded. 

I did download the chrome 95 driver (same as chrome itself) and added location to `.bash_profile`.

Any ideas?

```bash
(BINGIMG) Ember:bing_images me$ python download.py
Save path: /Users/me/Documents/_testImages/train_images/bing/socks/dl_001
Traceback (most recent call last):
  File "download.py", line 3, in <module>
    bing.download_images("socks",
  File "/Users/me/Documents/bing_images/bing_images/bing.py", line 58, in download_images
    urls = fetch_image_urls(query, max_number, file_type, filters)
  File "/Users/me/Documents/bing_images/bing_images/bing.py", line 28, in fetch_image_urls
    urls = crawl_image_urls(keywords, filters, limit)
  File "/Users/me/Documents/bing_images/bing_images/crawler.py", line 58, in crawl_image_urls
    image_urls = image_url_from_webpage(driver, max_number)
  File "/Users/me/Documents/bing_images/bing_images/crawler.py", line 35, in image_url_from_webpage
    smb[0].click()
  File "/opt/anaconda3/envs/BINGIMG/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/anaconda3/envs/BINGIMG/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "/opt/anaconda3/envs/BINGIMG/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/envs/BINGIMG/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a class="btn_seemore cbtn mBtn" role="button" href="javascript:void(0);" h="ID=images,6761.1">...</a> is not clickable at point (960, 26). Other element would receive the click: <div class="it">...</div>
  (Session info: chrome=95.0.4638.69)
Stacktrace:
0   chromedriver                        0x0000000109b79bb9 chromedriver + 2747321
1   chromedriver                        0x000000010a22fe03 chromedriver + 9784835
2   chromedriver                        0x0000000109906118 chromedriver + 176408
3   chromedriver                        0x0000000109941e21 chromedriver + 421409
4   chromedriver                        0x000000010993fa7e chromedriver + 412286
5   chromedriver                        0x000000010993d25a chromedriver + 402010
6   chromedriver                        0x000000010993bea7 chromedriver + 396967
7   chromedriver                        0x000000010992fe49 chromedriver + 347721
8   chromedriver                        0x0000000109957da2 chromedriver + 511394
9   chromedriver                        0x000000010992fbd5 chromedriver + 347093
10  chromedriver                        0x000000010995801e chromedriver + 512030
11  chromedriver                        0x000000010996a2fb chromedriver + 586491
12  chromedriver                        0x0000000109957fc3 chromedriver + 511939
13  chromedriver                        0x000000010992e40e chromedriver + 341006
14  chromedriver                        0x000000010992f735 chromedriver + 345909
15  chromedriver                        0x0000000109b405df chromedriver + 2512351
16  chromedriver                        0x0000000109b5326f chromedriver + 2589295
17  chromedriver                        0x0000000109b24cbb chromedriver + 2399419
18  chromedriver                        0x0000000109b546ea chromedriver + 2594538
19  chromedriver                        0x0000000109b35c8c chromedriver + 2469004
20  chromedriver                        0x0000000109b6df58 chromedriver + 2699096
21  chromedriver                        0x0000000109b6e0e1 chromedriver + 2699489
22  chromedriver                        0x0000000109b7ebc8 chromedriver + 2767816
23  libsystem_pthread.dylib             0x00007fff2051f8fc _pthread_start + 224
24  libsystem_pthread.dylib             0x00007fff2051b443 thread_start + 15
```

**Comment by CatchZeng** [comment]
Can you provide more specific environmental information?

My environment is as follows, verified that there is no problem.

- chrome 96.0.4664.45
- driver 96.0.4664.35
- mac OS 12.0.1

```sh
❯ conda create -n bing-images python=3.8.5
❯ conda activate bing-images
❯ export PATH=/Users/catchzeng/chromedriver:$PATH
❯ which chromedriver
/Users/catchzeng/chromedriver/chromedriver
❯ python download.py
Save path: /Users/catchzeng/Desktop/cat
Crawled 70 image urls.
Downloading images
#1 https://pngimg.com/uploads/cat/cat_PNG50449.png Downloaded
#2 https://purepng.com/public/uploads/large/purepng.com-catanimalscat-981524673949tj5ns.png Downloaded
#3 https://pngimg.com/uploads/cat/cat_PNG50448.png Downloaded
#4 https://pngimg.com/uploads/cat/cat_PNG50445.png Downloaded
#5 http://pngimg.com/uploads/cat/cat_PNG50482.png Downloaded
#6 http://purepng.com/public/uploads/large/purepng.com-sitting-catcatcatsanimalspetscute-cat-25152016380020k8o.png Downloaded
#7 https://purepng.com/public/uploads/large/515023057367pjqxmsnx7rgiihwwfa1yopebtptssyevfbjqwwbw8cxyucv6srtcaraobaotirnmd7zjkf3hi7oyexhybu0rkyuafuwk0hnxr5h.png Downloaded
#8 https://purepng.com/public/uploads/large/515023079169r5z6n4yjylprjqgiee36v9xirrxktv1oqnq4xbl9fzzxdbwpcsjfbypqjmwak4vfimpjchla8rxfuhpo7wdsrwf1gixcaxee7in.png Downloaded
#9 https://pngimg.com/uploads/cat/cat_PNG100.png Downloaded
#10 https://pngimg.com/uploads/cat/cat_PNG50479.png Downloaded
#11 https://pngimg.com/uploads/cat/cat_PNG50447.png Downloaded
#12 https://pngimg.com/uploads/cat/cat_PNG50433.png Downloaded
#13 https://purepng.com/public/uploads/large/purepng.com-catcat-animal-981524644802hvred.png Downloaded
#14 https://pngimg.com/uploads/cat/cat_PNG50440.png Downloaded
#15 https://purepng.com/public/uploads/large/purepng.com-cat-cuteanimalscats-115205020723cicy.png Downloaded
#16 https://pngimg.com/uploads/cat/cat_PNG113.png Downloaded
#17 https://pngimg.com/uploads/cat/cat_PNG50430.png Downloaded
#18 http://pngimg.com/uploads/cat/cat_PNG50424.png Downloaded
#19 https://pre00.deviantart.net/dc4a/th/pre/f/2017/362/3/d/cat_png_2_by_bouzid27-dby5uu3.png Downloaded
#20 https://pngimg.com/uploads/cat/cat_PNG50545.png Downloaded
Renaming images
Finished renaming
Done
Elapsed time: 86.24s
```

**Comment by KeygenOld** [comment]
Sure, sorry about that.

macOS 11.6 (20G165)
Google Chrome: 95.0.4638.69 (Official Build) (x86_64)
ChromeDriver: 95.0.4638.69

I think I setup conda with python 3.8. I'll update to 3.8.5 and see if it makes any difference.

**Comment by KeygenOld** [comment]
Well, I found that Google Chrome was trying to update itself, so it was looking for the newer chrome driver when I ran the python script. So I updated Chrome, trashed the old drivers and downloaded the latest one and placed it in the PATH. Still got the same errors though.

I'm going to try to boot in safe mode and then reboot again to make sure nothing squirrely is going on. I'm now using the same version of python, Chrome and ChromeDriver as you are.

**Comment by KeygenOld** [comment]
Okay, so I safe booted, ran daily weekly monthly maintenance cron jobs and restarted again. Have made some progress.

• single word searches work
• multiple word searches fail

### This Works
```python
from bing_images import bing

bing.download_images("cat",
                      100,
                      output_dir="/Users/me/Desktop/cat",
                      pool_size=10,
                      force_replace=True)
```
### This errors out the same way as before
```python
from bing_images import bing

bing.download_images("old cat",
                      100,
                      output_dir="/Users/me/Desktop/cat",
                      pool_size=10,
                      force_replace=True)
```

Using two words it does launch Chrome, the correct search terms are used, images load, page scrolls down, etc, but then the same error happens in terminal and it doesn't download anything.

**Comment by CatchZeng** [comment]
I have tried it and everything is fine, as shown in the picture below. 

<img width="1385" alt="" src="https://user-images.githubusercontent.com/10027281/141930025-8da60516-5b1b-4d54-8640-bc1c5833bb8e.png">

Can you provide the error logs?

**Comment by CatchZeng** [comment]
@KeygenLLC  I will close this issue temporarily, if you still have questions, you can reopen it again.

**Comment by KeygenOld** [comment]
Sorry for the delay. Been busy with other work.

strange. I have it in a virtual env so not sure what might be causing a conflict.

Which log do you need to see the output of? Just want to make sure I grab the correct one.

Thanks

**Comment by CatchZeng** [comment]
You can use conda to create a new environment to verify it, the code is as follows.

```zsh
❯ conda create -n bing-images python=3.8.5
❯ conda activate bing-images
❯ pip install bing-images
```

if there is an error, please copy the error log here for communication.

**Comment by KeygenOld** [comment]
Will do. thanks

**Comment by KeygenOld** [comment]
Well, good news is it worked. :)

Not sure if it's because I had a lower version of python at first, or maybe the env just got corrupted somehow. I didn't install any other packages, so... idk. I tend to get weird behavior like this that turns out to be more like ghosts in the machine than actual bugs.

Either way, it is working. Thanks for the help and for the cool tool.
